### ISSUE TITLE
how long can a video be for transcription?

### ISSUE THREAD

**Issue by deadcoder0904** [sensahin/YouWhisper#1]
i've read whisper processes videos in 30-second chunks.

my question is how long can the video be transcribed by whisper? 1-hour long, 8-hour long? should a video be used or audio for faster transcription?

i used your code on https://huggingface.co/spaces/sensahin/YouWhisper on [a 15 mins video](https://www.youtube.com/watch?v=-TOYJHax5x8) & it accurately transcribed it into ~4117 words.

is there an upper limit? does the program `youwhisper` cut it into chunks 30-second chunks? i haven't used python in like 5 years so not totally sure about the code.

**Comment by sensahin** [comment]
I think this question need to be asked at Whisper official forum. I couldn't find an exact answer for this as well. I tried 1 hour 30 minute long video and it did work well. So i am not sure what the limit is.

Here is a similar question on Whisper discussion page:

https://github.com/openai/whisper/discussions/136

**Comment by sensahin** [comment]
Since this is related with official Whisper library, i close this issue.

**Comment by deadcoder0904** [comment]
haha the issue you linked to was asked by me only. honestly didn't understand what that guy bcz of jargon said & my lack of knowledge so i thought you had an answer.
